name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Despliega cuando se hace un push a la rama principal (o la que uses)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push https://github.com/${{ github.repository }}.git HEAD:gh-pages
        env:
          GH_TOKEN: ${{ secrets.pages }}
